version: '3'
services:
  mongodb:
    image:
      mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./storage/db:/data/db
  app:
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - mongodb